language: scala

scala:
  - 2.10.7
  - 2.11.12
  - 2.12.6
  - 2.13.0-M4
jdk:
  - oraclejdk8
env:
  matrix:
    - SCALAJS_VERSION=
    - SCALAJS_VERSION=0.6.23
    - SCALAJS_VERSION=1.0.0-M3

matrix:
  exclude:
    # 2.10 is not supported in Scala.js 1.x
    - scala: 2.10.7
      env: SCALAJS_VERSION=1.0.0-M3

    # 2.13.0-M4 is not available in Scala.js 1.0.0-M3
    - scala: 2.13.0-M4
      env: SCALAJS_VERSION=1.0.0-M3

    # Scala.js 1.0.0-M3 does not have the fix for #3227 yet
    - scala: 2.11.12
      env: SCALAJS_VERSION=1.0.0-M3

script:
  - |
    if [ "$SCALAJS_VERSION" = "" ]; then
      PROJECT_NAME="reflectJVM"
    else
      PROJECT_NAME="reflectJS"
    fi
  - sbt ++$TRAVIS_SCALA_VERSION $PROJECT_NAME/test
  - sbt ++$TRAVIS_SCALA_VERSION $PROJECT_NAME/doc

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
